---
kind: pipeline
name: DRT React
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: Unit tests
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20.19
    commands:
      - /root/entrypoint.sh
      - npm ci
      - npm run test-ci

    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
      ENV_LOG_LEVEL: ERROR
      KEYTOOL_PASSWORD:
        from_secret: KEYTOOL_PASSWORD

  - name: Slack notification
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: devs
      template: "*{{repo.name}}: _{{build.status}}_*\nCompleted build *{{build.number}}* after *{{since build.started}}* on *{{build.branch}}*\n{{build.link}}\n"
      username: drone
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status:
        - success
        - failure
      event:
        - push
    depends_on:
      - Unit tests
...
