name: 'Deploy Storybook to GitHub Pages'
description: 'Build and deploy storybook code to GitHub pages'
branding:
  icon: upload-cloud
  color: red
inputs:
  checkout:
    description: 'Specifies if this action should checkout the code'
    required: false
    default: 'true'
  path:
    description: 'Specifies the path of the static assets after building'
    required: false
    # TODO: where does storybook output by default?
    default: 'storybook-static'
  install_yarn:
    description: 'Install yarn.'
    required: false
    default: 'npm install -g yarn'
  install_command:
    description: 'Specifies the command to run the installation.'
    required: false
    default: 'yarn install --immutable --immutable-cache --check-cache'
  build_command:
    description: 'Specifies the command to run after npm ci for the build'
    required: false
    default: 'yarn build-storybook'
outputs:
  page_url:
    description: "The URL of the page"
    value: ${{ steps.deploy.outputs.page_url }}

  

runs:
  using: 'ubuntu-latest'
  steps:
    - name: Checkout if required
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4

    - name: 'Build'
      shell: bash
      run: |
        echo "::group::Build"
        corepack enable
        ${{ inputs.install_yarn }}
        ${{ inputs.install_command }}
        ${{ inputs.build_command }}
        echo "::endgroup::"

    - name: 'upload'
      uses: actions/upload-pages-artifact@v3
      with: 
        path: ${{ inputs.path }}

    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ github.token }}

    - name: Print footer
      shell: bash
      run: |
        echo "" >> $GITHUB_STEP_SUMMARY
