on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from
      - "storybook-publishing-fix"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: actions/action
      with:
        path: build # change to your build folder
