on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from
      - "storybook-publishing-fix"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: checkout-actions
      uses : "actions/checkout@v4"
    - id: build-publish
      uses: ./.github/actions/publish
