on:
  push:
    branches:
      - "main"
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - id: checkout-actions
      uses : "actions/checkout@v4"
    - id: build-publish
      uses: ./.github/actions/publish
