on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - id: checkout-actions
      uses : "actions/checkout@v4"
    - id: build-publish
      uses: ./.github/actions/test
